# Basic
f = fn(x: Int){ x + 1 }
if f.call(1) != 2; puts "ng 1"; end

# Lambda in a method
class A
  def self.foo -> Int
    fn(x: Int){ x + 1 }.call(1)
  end
end
if A.foo != 2; puts "ng 2"; end

# Capturing free vars
a = 1
g = fn(x: Int){
  b = 2
  h = fn(y: Int) {
    a + b + x + y
  }
  h.call(3)
}
unless g.call(4) == 10; puts "ng 3"; end

# Capturing bool
t = true
f2 = fn(x: Int) { t }
unless f2.call(0); puts "ng 4"; end

puts "ok"
