# Basic
if fn(){ false }.call; puts "ng 0"; end
f = fn(x: Int){ x + 1 }
if f.call(1) != 2; puts "ng 1"; end
ff = fn(x: Int, y: Int){ x + y }
if ff.call(1, 2) != 3; puts "ng 1-1"; end

# Lambda in a method
class A
  def self.foo -> Int
    fn(x: Int){ x + 1 }.call(1)
  end
end
if A.foo != 2; puts "ng 2"; end

# Capturing free vars
a = 1
g = fn(x: Int){
  b = 2
  h = fn(y: Int, z: Int) {
    a + b + x + y + z
  }
  h.call(3, 4)
}
unless g.call(5) == 15; puts "ng 3"; end

# Capturing bool
t = true
f2 = fn(x: Int) { t }
unless f2.call(0); puts "ng 4"; end

puts "ok"
