if false then puts "ng 1" end
if !true then puts "ng 2.5" end
if !(true && true) then puts "ng 3" end
if  (true && false) then puts "ng 4" end
if  (false && true) then puts "ng 5" end
if  (false && false) then puts "ng 6" end
if !(true || true) then puts "ng 11" end
if !(true || false) then puts "ng 12" end
if !(false || true) then puts "ng 13" end
if  (false || false) then puts "ng 14" end

puts "ok"
