class Main
  def self.countdown(i: Int, count: Int) -> Int
    sleep_sec(0)
    if i > 0
      # Test implicit return
      countdown(i - 1, count + 1)
    else
      count + 1
    end
  end

  def self.run()
    # countdown from 3 should have 4 steps (3, 2, 1, 0)
    let total_steps = countdown(3, 0)
    unless total_steps == 4
      puts "ng: countdown2 total steps"
    end
  end
end

Main.run
puts "ok"
