class Main
  def self.foo(log: Array<Int>)
    var i = 1
    while i < 3
      var j = 2
      while j < 4
        log.push(i * j)
        j += 1
      end
      i += 1
    end
  end

  def self.run()
    let log = Array<Int>.new
    foo(log)
    # i=1,j=2: 2; i=1,j=3: 3; i=2,j=2: 4; i=2,j=3: 6
    unless (log[0] == 2 and log[1] == 3 and log[2] == 4 and log[3] == 6 and log.length == 4)
      puts "ng: while_sync"
    end
  end
end

Main.run
puts "ok"
