use crate::lexer::Cursor;
use std::backtrace::Backtrace;

#[derive(thiserror::Error, Debug)]
pub enum Error {
    /// Error on parsing
    #[error("{msg})")]
    ParseError {
        msg: String,
        /// Error report generated by ariadne. (not a String because it may contain filepath, which
        /// may not be UTF-8)
        report: Vec<u8>,
    },
    /// Error on tokenizing
    #[error("{msg}")]
    LexError {
        msg: String,
        backtrace: Backtrace,
        location: Cursor,
    },
}
