[package]
name = "ext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
shiika_ffi = { path = "../../../lib/shiika_ffi" }
shiika_ffi_macro = { path = "../../../lib/shiika_ffi_macro" }
tokio = { version = "1.35.1", features = ["full"] }
bdwgc-alloc = { version = "0.6.5", default-features=false, features = ["cmake"] }
